### ISSUE TITLE
Nil error in detect_format

### ISSUE THREAD

**Issue by pendletons** [toy/image_size#20]
I am running image_optim, but keep getting this error: (it does work with image_optim v0.31.0, so I think the image_size update caused it)
```ruby
> image_optim --verbose -r .
image_optim v0.31.1
config:
  svgo: false
  skip_missing_workers: true
  verbose: true
nice: 10
threads: 8
pack: true
skip_missing_workers: true
allow_lossy: false
cache_dir: 
cache_worker_digests: false
timeout: 
image_optim_pack: all bins from /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64 worked
PATH: /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64:/Users/me/.rbenv/versions/3.1.2/bin:/opt/homebrew/Cellar/rbenv/1.2.0/libexec:/Users/me/.asdf/shims:/Users/me/.asdf/bin:/Users/me/.rbenv/shims:/opt/homebrew/opt/mysql@5.7/bin:/Users/me/Library/Python/2.7/bin:/Users/me/.yarn/bin:/Users/me/.config/yarn/global/node_modules/.bin:/Users/me/.cargo/bin:.git/safe/../../bin:/Users/me/.bin:/usr/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/Library/Apple/usr/bin:/Users/me/code/webdoctor/node_modules/.bin:/opt/homebrew/opt/fzf/bin:/Users/me/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/Users/me/.antigen/bundles/Aloxaf/fzf-tab:/Users/me/.antigen/bundles/Tarrasch/zsh-bd:/Users/me/.antigen/bundles/supercrabtree/k:/Users/me/.antigen/bundles/zsh-users/zsh-autosuggestions:/Users/me/.antigen/bundles/tymm/zsh-directory-history:/Users/me/.antigen/bundles/smallhadroncollider/antigen-git-rebase:/Users/me/.antigen/bundles/romkatv/powerlevel10k:/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/vendor
Resolved pngcrush 1.8.13 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/pngcrush
Resolved pngout 20200115 at /opt/homebrew/bin/pngout
Resolved advpng 2.3 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/advpng
Resolved optipng 0.7.7 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/optipng
Resolved pngquant 2.17.0 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/pngquant
Resolved oxipng 5.0.1 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/oxipng
Resolved jhead 3.04 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/jhead
Resolved jpegtran 9e at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/jpegtran
Resolved jpegoptim 1.4.7 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/jpegoptim
Resolved jpegrescan 1a762f62 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/vendor/jpegrescan
Resolved gifsicle 1.93 at /Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim_pack-0.8.0.20220418/vendor/darwin-x86_64/gifsicle
Workers by format:
jpeg:
  jhead:
  jpegoptim:
    allow_lossy: false
    strip: ["all"]
    max_quality: 100
  jpegtran:
    copy_chunks: false
    progressive: true
    jpegrescan: true
png:
  pngcrush:
    chunks: ["alla"]
    fix: false
    brute: false
    blacken: true
  optipng:
    level: 6
    interlace: false
    strip: true
  oxipng:
    level: 3
    interlace: false
    strip: true
  pngquant:
    allow_lossy: false
    max_colors: 256
    quality: 100..100
    speed: 3
  pngout:
    copy_chunks: false
    strategy: 0
  advpng:
    level: 4
gif:
  gifsicle:
    interlace: false
    level: 3
    careful: false
  gifsicle:
    interlace: true
    level: 3
    careful: false
undefined method `[]' for nil:NilClass

    when head[0, 6] =~ /GIF8[79]a/                                then :gif
             ^^^^^^
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size.rb:79:in `detect_format'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size.rb:51:in `block in initialize'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `block in open'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `open'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `open'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size/reader.rb:18:in `open'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size.rb:50:in `initialize'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size.rb:35:in `new'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_size-3.0.1/lib/image_size.rb:35:in `path'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/image_meta.rb:9:in `format_for_path'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/path.rb:68:in `image_format'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim.rb:109:in `workers_for_image'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim.rb:224:in `optimizable?'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:108:in `block in find_to_optimize_recursive'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/3.1.0/find.rb:49:in `block (2 levels) in find'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/3.1.0/find.rb:48:in `catch'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/3.1.0/find.rb:48:in `block in find'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/3.1.0/find.rb:43:in `each'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/3.1.0/find.rb:43:in `find'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:105:in `find_to_optimize_recursive'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:92:in `block in find_to_optimize'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:83:in `each'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:83:in `find_to_optimize'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/lib/image_optim/runner.rb:60:in `run!'
/Users/me/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/image_optim-0.31.1/bin/image_optim:21:in `<top (required)>'
/Users/me/.rbenv/versions/3.1.2/bin/image_optim:25:in `load'
/Users/me/.rbenv/versions/3.1.2/bin/image_optim:25:in `<main>'
```
My gemfile & lock:
```ruby
# gemfile
source 'https://rubygems.org'

gem 'overcommit'
gem 'brakeman'
gem 'bundler'
gem 'haml-lint'
gem 'image_optim'
gem 'json'
gem 'mdl'
gem 'pronto'
gem 'pronto-haml'
gem 'pronto-rails_best_practices'
gem 'rubocop', require: false
gem 'rubocop-minitest', require: false
gem 'rubocop-performance', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false

# lock
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (7.0.2.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    ast (2.4.2)
    brakeman (5.2.2)
    chef-utils (17.10.0)
      concurrent-ruby
    childprocess (4.1.0)
    code_analyzer (0.5.5)
      sexp_processor
    concurrent-ruby (1.1.10)
    erubis (2.7.0)
    exifr (1.3.9)
    faraday (1.10.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0)
      faraday-multipart (~> 1.0)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.0)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      faraday-retry (~> 1.0)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-multipart (1.0.3)
      multipart-post (>= 1.2, < 3)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    faraday-retry (1.0.3)
    fspath (3.1.2)
    gitlab (4.18.0)
      httparty (~> 0.18)
      terminal-table (>= 1.5.1)
    haml (5.2.2)
      temple (>= 0.8.0)
      tilt
    haml-lint (0.999.999)
      haml_lint
    haml_lint (0.40.0)
      haml (>= 4.0, < 5.3)
      parallel (~> 1.10)
      rainbow
      rubocop (>= 0.50.0)
      sysexits (~> 1.1)
    httparty (0.20.0)
      mime-types (~> 3.0)
      multi_xml (>= 0.5.2)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    image_optim (0.31.1)
      exifr (~> 1.2, >= 1.2.2)
      fspath (~> 3.0)
      image_size (>= 1.5, < 4)
      in_threads (~> 1.3)
      progress (~> 3.0, >= 3.0.1)
    image_size (3.0.1)
    in_threads (1.6.0)
    iniparse (1.5.0)
    json (2.6.1)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    mdl (0.11.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.1)
      mixlib-cli (~> 2.1, >= 2.1.1)
      mixlib-config (>= 2.2.1, < 4)
      mixlib-shellout
    mime-types (3.4.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2022.0105)
    minitest (5.15.0)
    mixlib-cli (2.1.8)
    mixlib-config (3.0.9)
      tomlrb
    mixlib-shellout (3.2.7)
      chef-utils
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    octokit (4.22.0)
      faraday (>= 0.9)
      sawyer (~> 0.8.0, >= 0.5.3)
    overcommit (0.58.0)
      childprocess (>= 0.6.3, < 5)
      iniparse (~> 1.4)
      rexml (~> 3.2)
    parallel (1.22.1)
    parser (3.1.2.0)
      ast (~> 2.4.1)
    progress (3.6.0)
    pronto (0.11.0)
      gitlab (~> 4.4, >= 4.4.0)
      httparty (>= 0.13.7)
      octokit (~> 4.7, >= 4.7.0)
      rainbow (>= 2.2, < 4.0)
      rexml (~> 3.2)
      rugged (>= 0.23.0, < 1.1.0)
      thor (>= 0.20.3, < 2.0)
    pronto-haml (0.11.1)
      haml_lint (~> 0.23)
      pronto (~> 0.11.0)
    pronto-rails_best_practices (0.11.0)
      pronto (~> 0.11.0)
      rails_best_practices (~> 1.16, >= 1.15.0)
    public_suffix (4.0.7)
    rack (2.2.3)
    rails_best_practices (1.23.1)
      activesupport
      code_analyzer (~> 0.5.5)
      erubis
      i18n
      json
      require_all (~> 3.0)
      ruby-progressbar
    rainbow (3.1.1)
    regexp_parser (2.3.1)
    require_all (3.0.0)
    rexml (3.2.5)
    rubocop (1.28.2)
      parallel (~> 1.10)
      parser (>= 3.1.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.17.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.17.0)
      parser (>= 3.1.1.0)
    rubocop-minitest (0.19.1)
      rubocop (>= 0.90, < 2.0)
    rubocop-performance (1.13.3)
      rubocop (>= 1.7.0, < 2.0)
      rubocop-ast (>= 0.4.0)
    rubocop-rails (2.14.2)
      activesupport (>= 4.2.0)
      rack (>= 1.1)
      rubocop (>= 1.7.0, < 2.0)
    rubocop-rspec (2.10.0)
      rubocop (~> 1.19)
    ruby-progressbar (1.11.0)
    ruby2_keywords (0.0.5)
    rugged (1.0.1)
    sawyer (0.8.2)
      addressable (>= 2.3.5)
      faraday (> 0.8, < 2.0)
    sexp_processor (4.16.1)
    sysexits (1.2.0)
    temple (0.8.2)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    thor (1.2.1)
    tilt (2.0.10)
    tomlrb (2.0.1)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    unicode-display_width (2.1.0)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  brakeman
  bundler
  haml-lint
  image_optim
  json
  mdl
  overcommit
  pronto
  pronto-haml
  pronto-rails_best_practices
  rubocop
  rubocop-minitest
  rubocop-performance
  rubocop-rails
  rubocop-rspec

BUNDLED WITH
   2.3.12
```

**Comment by toy** [comment]
Thank you for opening the issue!
My first guess is that empty file is not handled properly, that should be easy to fix.

**Comment by pendletons** [comment]
Works great, thanks for the quick turnaround!
